version: '2.17.2'

services:
    aes_encrypt:
        images: aes_encrypt
        volumes:
          -  /home/ubuntustage/Desktop/rsfaas/Inputs_Faas:/Inputs_Faas
          -  /home/ubuntustage/Desktop/rsfaas/Outputs_Faas:/Outputs_Faas
        command:
        
    hash:
        images: hash
        volumes:
          -  /home/ubuntustage/Desktop/rsfaas/Inputs_Faas:/Inputs_Faas
          -  /home/ubuntustage/Desktop/rsfaas/Outputs_Faas:/Outputs_Faas
        command:
        
    aes_decrypt: 
        images: aes_decrypt
        volumes: 
          -  /home/ubuntustage/Desktop/rsfaas/Outputs_Faas:/Outputs_Faas
        depends_on:
            hash:
              condition: service_completed_successfully
    
    actions_executed:
        images: actions_executed
        volumes: 
          -  /home/ubuntustage/Desktop/rsfaas/Outputs_Faas:/Outputs_Faas
        depends_on:
            hash:
              condition: service_completed_successfully
   
